version: '3.8'

services:
  blood-loss-calc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
      - ./resources:/app/resources
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/blood-loss-images;
      /usr/bin/mc policy set public myminio/blood-loss-images;
      echo 'Minio initialized successfully';
      tail -f /dev/null
      "
    restart: on-failure

volumes:
  minio_data: